# Generated by Django 5.2.17 on 2026-09-17 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], default='email', max_length=10),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(db_index=True, max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ta', 'Tamil'), ('ml', 'Malayalam')], max_length=8)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['notification_type', 'channel', 'language'],
                'constraints': [models.UniqueConstraint(fields=('notification_type', 'channel', 'language'), name='unique_template_per_type_channel_language')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fcm_token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('iOS', 'iOS')], max_length=10)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
            },
        ),
        enable_rls('push_subscriptions'),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
                'constraints': [models.UniqueConstraint(fields=('user', 'notification_type', 'channel'), name='unique_preference_per_user_type_channel')],
            },
        ),
        enable_rls('notification_preferences'),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('send_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_notifications',
                'ordering': ['send_at'],
                'indexes': [models.Index(fields=['status', 'send_at'], name='scheduled_n_status_1106b7_idx')],
            },
        ),
        enable_rls('scheduled_notifications'),
    ]
