# Generated by Django 5.2.17 on 2026-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationlog_recipient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
