# Generated by Django 5.2.17 on 2026-10-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('notifications', '0006_scheduled_notification_failed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_subscriptions', to='devices.appinstallation'),
        ),
    ]
