# Generated by Django 5.2.15 on 2026-07-04 02:51

import apps.operations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0005_admission_advance_collected_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('internet_wifi', 'Internet / WiFi'), ('housekeeping', 'Housekeeping'), ('security', 'Security'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.operations.models.complaint_attachment_path)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_raised', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='residents.resident')),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_comments', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.complaint')),
            ],
            options={
                'db_table': 'complaint_comments',
                'ordering': ['created_at'],
            },
        ),
        # Invariant 1: tenant isolation enforced at the DB level.
        enable_rls('complaints'),
        enable_rls('complaint_comments'),
    ]
