# Generated by Django 5.2.15 on 2026-07-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='trial_reminder_first_days_before',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='trial_reminder_second_days_before',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
