# Generated by Django 5.2.17 on 2026-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformconfig_trial_reminder_first_days_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='min_billable_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
