# Generated by Django 5.2.17 on 2026-09-10 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment'),
        ('residents', '0006_alter_admission_contracted_sharing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('resident', 'period_start'), name='unique_invoice_per_resident_period'),
        ),
    ]
