# Generated by Django 5.2.15 on 2026-07-04 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_properties', models.PositiveIntegerField(blank=True, null=True)),
                ('max_residents_per_property', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_trial_plan', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=100)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('payment_failed_at', models.DateTimeField(blank=True, null=True)),
                ('max_properties_override', models.PositiveIntegerField(blank=True, null=True)),
                ('max_residents_override', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.tenant')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscription_payments',
                'ordering': ['-created_at'],
            },
        ),
        # Invariant 1: tenant isolation enforced at the DB level.
        enable_rls('subscription_payments'),
    ]
