# Generated by Django 5.2.17 on 2026-08-11 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': [models.OrderBy(models.F('price_per_month'), nulls_last=True), 'name']},
        ),
        migrations.AddField(
            model_name='plan',
            name='pricing_type',
            field=models.CharField(choices=[('flat_monthly', 'Flat monthly'), ('per_bed_monthly', 'Per bed monthly')], default='flat_monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BedLedgerEntry',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_id', models.UUIDField()),
                ('event', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bed_ledger_entries',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['tenant_id', 'occurred_at'], name='bed_ledger__tenant__6e9acf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billed_bed_count_start', models.PositiveIntegerField()),
                ('billed_bed_count_end', models.PositiveIntegerField()),
                ('razorpay_invoice_id', models.CharField(blank=True, max_length=100)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscription_invoices',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoiceLine',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('addons', models.JSONField(blank=True, default=list)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='subscriptions.subscriptioninvoice')),
            ],
            options={
                'db_table': 'subscription_invoice_lines',
            },
        ),
        migrations.CreateModel(
            name='PlanBedTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('up_to_beds', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_per_bed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_tiers', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'plan_bed_tiers',
                'ordering': [models.OrderBy(models.F('up_to_beds'), nulls_last=True)],
                'constraints': [models.UniqueConstraint(fields=('plan', 'up_to_beds'), name='unique_bed_tier_ceiling_per_plan')],
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.UniqueConstraint(fields=('subscription', 'period_start'), name='unique_invoice_per_cycle'),
        ),
        # Invariant 1: tenant isolation enforced at the DB level for every
        # new TenantModelMixin table (matches 0001_initial's SubscriptionPayment).
        enable_rls('bed_ledger_entries'),
        enable_rls('subscription_invoices'),
        enable_rls('subscription_invoice_lines'),
    ]
