# Generated by Django 5.2.17 on 2026-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_backfill_bed_ledger'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptionpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_payment_id', ''), _negated=True), fields=('razorpay_payment_id',), name='unique_razorpay_payment_id'),
        ),
    ]
