# Generated by Django 5.2.15 on 2026-07-03 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('boys_hostel', 'Boys Hostel'), ('girls_hostel', 'Girls Hostel'), ('pg', 'PG'), ('co_living', 'Co-Living Space')], max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='properties.property')),
            ],
            options={
                'db_table': 'floors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStaffAssignment',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='properties.property')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_staff_assignments',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('sharing_type', models.PositiveSmallIntegerField(choices=[(1, '1-sharing'), (2, '2-sharing'), (3, '3-sharing'), (4, '4-sharing')])),
                ('category', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=10)),
                ('rack_rate_with_food', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rack_rate_without_food', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=12)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.floor')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=20)),
                ('rack_rate_with_food_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rack_rate_without_food_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=12)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.room')),
            ],
            options={
                'db_table': 'beds',
                'ordering': ['bed_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('property', 'order'), name='unique_floor_order_per_property'),
        ),
        migrations.AddConstraint(
            model_name='propertystaffassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'property'), name='unique_staff_property_assignment'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'room_number'), name='unique_room_number_per_floor'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('room', 'bed_number'), name='unique_bed_number_per_room'),
        ),
        # Invariant 1: tenant isolation enforced at the DB level for every
        # business table introduced by this module.
        enable_rls('properties'),
        enable_rls('floors'),
        enable_rls('rooms'),
        enable_rls('beds'),
        enable_rls('property_staff_assignments'),
    ]
