# Generated by Django 5.2.15 on 2026-07-03 02:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySettings',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_transfer_rent_timing', models.CharField(choices=[('immediate', 'Immediately'), ('next_billing_cycle', 'Next Billing Cycle')], default='next_billing_cycle', max_length=20)),
                ('late_payment_penalty_type', models.CharField(choices=[('none', 'No Penalty'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=10)),
                ('penalty_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('penalty_grace_days', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(30)])),
                ('penalty_applies_to', models.CharField(choices=[('full_invoice', 'Full Invoice Amount'), ('outstanding_balance', 'Outstanding Balance Only')], default='full_invoice', max_length=20)),
                ('penalty_compounding', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly')], default='one_time', max_length=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='properties.property')),
            ],
            options={
                'db_table': 'property_settings',
            },
        ),
        # Invariant 1: tenant isolation enforced at the DB level.
        enable_rls('property_settings'),
    ]
