# Generated by Django 5.2.17 on 2026-10-06 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_room_sharing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('rooms', 'Rooms & Furnishing'), ('food', 'Food & Kitchen'), ('housekeeping', 'Housekeeping & Laundry'), ('connectivity', 'Internet & Entertainment'), ('utilities', 'Utilities & Comfort'), ('safety', 'Safety & Security'), ('recreation', 'Recreation & Common Areas'), ('parking', 'Parking & Transport'), ('services', 'Services & Support'), ('accessibility', 'Accessibility'), ('policies', 'Stay Policies')], db_index=True, max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_catalog',
                'ordering': ['category', 'display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TenantFeature',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant_features',
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'slug'), name='unique_tenant_feature_slug')],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.building')),
                ('catalog_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_features', to='properties.featurecatalog')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
                ('tenant_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_features', to='properties.tenantfeature')),
            ],
            options={
                'db_table': 'property_features',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('catalog_feature__isnull', False), ('tenant_feature__isnull', True)), models.Q(('catalog_feature__isnull', True), ('tenant_feature__isnull', False)), _connector='OR'), name='property_feature_catalog_xor_tenant'), models.CheckConstraint(condition=models.Q(('is_available', True), ('building__isnull', False), _connector='OR'), name='property_feature_suppression_requires_building'), models.UniqueConstraint(fields=('property', 'building', 'catalog_feature', 'tenant_feature'), name='unique_property_feature_assignment', nulls_distinct=False)],
            },
        ),
        # Invariant 1: tenant isolation enforced at the DB level.
        # feature_catalog is deliberately left out — it is platform-global
        # config (like plans / notification_templates) with no tenant_id.
        enable_rls('tenant_features'),
        enable_rls('property_features'),
    ]
