# Generated by Django 5.2.17 on 2026-10-09 16:37

import django.core.validators
from django.db import migrations, models

from apps.core.tenancy import tenant_context


def backfill_gender_preference(apps, schema_editor):
    """Existing gendered hostels keep their meaning in the new field; every
    other row keeps the 'unisex' column default."""
    Property = apps.get_model('properties', 'Property')
    # RLS is FORCE-enabled and no tenant GUC is set during a migration —
    # without is_super_admin these updates would silently match zero rows.
    with tenant_context(is_super_admin=True):
        Property.objects.filter(property_type='boys_hostel').update(gender_preference='male')
        Property.objects.filter(property_type='girls_hostel').update(gender_preference='female')


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_seed_feature_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gender_preference',
            field=models.CharField(choices=[('unisex', 'Unisex'), ('male', 'Male'), ('female', 'Female')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[1-9]\\d{5}$', 'Enter a valid 6-digit pincode.')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('boys_hostel', 'Boys Hostel'), ('girls_hostel', 'Girls Hostel'), ('hostel', 'Hostel'), ('pg', 'PG'), ('co_living', 'Co-Living Space')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='property_coordinates_both_or_neither'),
        ),
        migrations.RunPython(backfill_gender_preference, migrations.RunPython.noop),
    ]
