# Generated by Django 5.2.15 on 2026-07-03 02:38

import apps.residents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_propertysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('reserved', 'Reserved'), ('active', 'Active'), ('notice_period', 'Notice Period'), ('vacated', 'Vacated'), ('absconded', 'Absconded'), ('blacklisted', 'Blacklisted')], default='inquiry', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('permanent_address', models.TextField(blank=True)),
                ('current_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to=apps.residents.models.resident_document_path)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to=apps.residents.models.resident_document_path)),
                ('passport_number', models.CharField(blank=True, max_length=30)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='properties.property')),
            ],
            options={
                'db_table': 'residents',
            },
        ),
        # Invariant 1: tenant isolation enforced at the DB level.
        enable_rls('residents'),
    ]
