# Generated by Django 5.2.15 on 2026-07-03 02:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertysettings'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joining_date', models.DateField()),
                ('billing_mode', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10)),
                ('expected_stay_duration', models.CharField(blank=True, max_length=50)),
                ('contracted_sharing_type', models.PositiveSmallIntegerField(choices=[(1, '1-sharing'), (2, '2-sharing'), (3, '3-sharing'), (4, '4-sharing')])),
                ('contracted_room_category', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=10)),
                ('food_preference', models.CharField(choices=[('with_food', 'With Food'), ('without_food', 'Without Food')], max_length=15)),
                ('contracted_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('first_month_billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('first_month_billing_note', models.TextField(blank=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='properties.bed')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_recorded', to=settings.AUTH_USER_MODEL)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admission', to='residents.resident')),
            ],
            options={
                'db_table': 'admissions',
            },
        ),
        # Invariant 1: tenant isolation enforced at the DB level.
        enable_rls('admissions'),
    ]
