# Generated by Django 5.2.15 on 2026-07-03 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertysettings'),
        ('residents', '0002_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contracted_sharing_type', models.PositiveSmallIntegerField(choices=[(1, '1-sharing'), (2, '2-sharing'), (3, '3-sharing'), (4, '4-sharing')])),
                ('contracted_room_category', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=10)),
                ('contracted_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_temporary', models.BooleanField(default=False)),
                ('temporary_since', models.DateField(blank=True, null=True)),
                ('expected_move_date', models.DateField(blank=True, null=True)),
                ('temporary_note', models.TextField(blank=True)),
                ('allocated_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='properties.bed')),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation', to='residents.resident')),
            ],
            options={
                'db_table': 'allocations',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_temporary', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('transfer_date', models.DateField()),
                ('previous_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rent_effective_date', models.DateField()),
                ('new_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='properties.bed')),
                ('previous_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='properties.bed')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_recorded', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='residents.resident')),
            ],
            options={
                'db_table': 'transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        # Invariant 1: tenant isolation enforced at the DB level.
        enable_rls('allocations'),
        enable_rls('transfers'),
    ]
