# Generated by Django 5.2.15 on 2026-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_allocation_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
