# Generated by Django 5.2.15 on 2026-07-04 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_admission_addons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='advance_collected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='advance_mode',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=15),
        ),
        migrations.CreateModel(
            name='AbscondedRecord',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('absconded_date', models.DateField()),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('absconded_note', models.TextField(blank=True)),
                ('advance_forfeited', models.BooleanField(default=True)),
                ('advance_applied_to_dues', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_dues', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dues_recovery_status', models.CharField(choices=[('outstanding', 'Outstanding'), ('partially_recovered', 'Partially Recovered'), ('written_off', 'Written Off')], default='outstanding', max_length=20)),
                ('dues_written_off_note', models.TextField(blank=True)),
                ('dues_written_off_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dues_written_off', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absconded_records_marked', to=settings.AUTH_USER_MODEL)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='absconded_record', to='residents.resident')),
            ],
            options={
                'db_table': 'absconded_records',
            },
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries_confirmed', to=settings.AUTH_USER_MODEL)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blacklist_entry', to='residents.resident')),
            ],
            options={
                'db_table': 'blacklist_entries',
            },
        ),
        migrations.CreateModel(
            name='Vacate',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_given_date', models.DateField()),
                ('expected_vacate_date', models.DateField()),
                ('actual_vacate_date', models.DateField(blank=True, null=True)),
                ('maintenance_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maintenance_deduction_note', models.TextField(blank=True)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('refund_mode', models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=15)),
                ('refund_note', models.TextField(blank=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vacate', to='residents.resident')),
                ('settled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacates_settled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacates',
            },
        ),
        # Invariant 1: tenant isolation enforced at the DB level.
        enable_rls('absconded_records'),
        enable_rls('blacklist_entries'),
        enable_rls('vacates'),
    ]
