# Generated by Django 5.2.15 on 2026-07-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_admission_advance_collected_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='contracted_sharing_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-sharing'), (2, '2-sharing'), (3, '3-sharing'), (4, '4-sharing'), (5, '5-sharing'), (6, '6-sharing'), (7, '7-sharing'), (8, '8-sharing')]),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='contracted_sharing_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-sharing'), (2, '2-sharing'), (3, '3-sharing'), (4, '4-sharing'), (5, '5-sharing'), (6, '6-sharing'), (7, '7-sharing'), (8, '8-sharing')]),
        ),
    ]
