# Generated by Django 5.2.17 on 2026-10-07 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_security_deposit_and_deposit_forfeit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacate',
            options={'ordering': ['notice_given_date', 'created_at']},
        ),
        migrations.AddField(
            model_name='vacate',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacate',
            name='cancelled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacates_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacate',
            name='cancelled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacate',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacates', to='residents.resident'),
        ),
        migrations.AddConstraint(
            model_name='vacate',
            constraint=models.UniqueConstraint(condition=models.Q(('actual_vacate_date__isnull', True), ('cancelled_date__isnull', True)), fields=('resident',), name='unique_open_vacate_per_resident'),
        ),
        migrations.AddConstraint(
            model_name='vacate',
            constraint=models.CheckConstraint(condition=models.Q(('actual_vacate_date__isnull', False), ('cancelled_date__isnull', False), _negated=True), name='vacate_not_both_cancelled_and_settled'),
        ),
    ]
