# Generated by Django 5.2.17 on 2026-10-08 17:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('flavor', models.CharField(choices=[('dev', 'Dev'), ('prod', 'Prod')], max_length=10)),
                ('build_mode', models.CharField(blank=True, max_length=16)),
                ('version_name', models.CharField(blank=True, max_length=64)),
                ('build_number', models.PositiveIntegerField()),
                ('package_id', models.CharField(blank=True, max_length=128)),
                ('os_name', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('os_sdk_int', models.PositiveIntegerField(blank=True, null=True)),
                ('device_manufacturer', models.CharField(blank=True, max_length=64)),
                ('device_model', models.CharField(blank=True, max_length=64)),
                ('is_physical', models.BooleanField(default=True)),
                ('screen_width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('pixel_ratio', models.FloatField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=16)),
                ('utc_offset_minutes', models.IntegerField(blank=True, null=True)),
                ('timezone_abbr', models.CharField(blank=True, max_length=16)),
                ('network_type', models.CharField(blank=True, max_length=32)),
                ('push_permission', models.CharField(blank=True, max_length=32)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('last_sync_seq', models.BigIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_installations',
            },
        ),
        migrations.CreateModel(
            name='AppInstallationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.PositiveIntegerField()),
                ('version_name', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='devices.appinstallation')),
            ],
            options={
                'verbose_name_plural': 'app installation history',
                'db_table': 'app_installation_history',
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppVersionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('flavor', models.CharField(choices=[('dev', 'Dev'), ('prod', 'Prod')], default='prod', max_length=10)),
                ('min_build', models.PositiveIntegerField(default=1, help_text='Builds below this are force-updated. Raise only after the new build is fully live in the store.', validators=[django.core.validators.MinValueValidator(1)])),
                ('latest_build', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('latest_version', models.CharField(blank=True, max_length=64)),
                ('store_url', models.URLField(blank=True, max_length=500)),
                ('release_notes', models.JSONField(blank=True, default=dict, help_text='{"en": "...", "te": "..."}')),
                ('soft_update_enabled', models.BooleanField(default=True)),
                ('maintenance_enabled', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(blank=True, max_length=500)),
                ('maintenance_expires_at', models.DateTimeField(blank=True, null=True)),
                ('check_interval_seconds', models.PositiveIntegerField(default=21600, validators=[django.core.validators.MinValueValidator(60)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'app version policies',
                'db_table': 'app_version_policies',
            },
        ),
        migrations.AddIndex(
            model_name='appinstallation',
            index=models.Index(fields=['platform', 'build_number'], name='appinst_platform_build_idx'),
        ),
        migrations.AddConstraint(
            model_name='appversionpolicy',
            constraint=models.UniqueConstraint(fields=('platform', 'flavor'), name='unique_app_policy_per_platform_flavor'),
        ),
    ]
